# Generated by Django 5.1.4 on 2024-12-12 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_project_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Service',
        ),
    ]
