# Generated by Django 5.1.4 on 2024-12-14 01:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateField(default=datetime.datetime(2024, 12, 14, 1, 11, 53, 361864, tzinfo=datetime.timezone.utc), verbose_name='Fecha de publicación'),
        ),
    ]
